SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[COSP] (
		[CodEmpresa]           [int] NOT NULL,
		[MANDT]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LEDNR]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[OBJNR]                [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GJAHR]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[WRTTP]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VERSN]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KSTAR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[HRKFT]                [nvarchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VRGNG]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBUND]                [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PARGB]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BEKNZ]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TWAER]                [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PERBL]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MEINH]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[WTG001]               [numeric](15, 2) NOT NULL,
		[WTG002]               [numeric](15, 2) NOT NULL,
		[WTG003]               [numeric](15, 2) NOT NULL,
		[WTG004]               [numeric](15, 2) NOT NULL,
		[WTG005]               [numeric](15, 2) NOT NULL,
		[WTG006]               [numeric](15, 2) NOT NULL,
		[WTG007]               [numeric](15, 2) NOT NULL,
		[WTG008]               [numeric](15, 2) NOT NULL,
		[WTG009]               [numeric](15, 2) NOT NULL,
		[WTG010]               [numeric](15, 2) NOT NULL,
		[WTG011]               [numeric](15, 2) NOT NULL,
		[WTG012]               [numeric](15, 2) NOT NULL,
		[WTG013]               [numeric](15, 2) NOT NULL,
		[WTG014]               [numeric](15, 2) NOT NULL,
		[WTG015]               [numeric](15, 2) NOT NULL,
		[WTG016]               [numeric](15, 2) NOT NULL,
		[WOG001]               [numeric](15, 2) NOT NULL,
		[WOG002]               [numeric](15, 2) NOT NULL,
		[WOG003]               [numeric](15, 2) NOT NULL,
		[WOG004]               [numeric](15, 2) NOT NULL,
		[WOG005]               [numeric](15, 2) NOT NULL,
		[WOG006]               [numeric](15, 2) NOT NULL,
		[WOG007]               [numeric](15, 2) NOT NULL,
		[WOG008]               [numeric](15, 2) NOT NULL,
		[WOG009]               [numeric](15, 2) NOT NULL,
		[WOG010]               [numeric](15, 2) NOT NULL,
		[WOG011]               [numeric](15, 2) NOT NULL,
		[WOG012]               [numeric](15, 2) NOT NULL,
		[WOG013]               [numeric](15, 2) NOT NULL,
		[WOG014]               [numeric](15, 2) NOT NULL,
		[WOG015]               [numeric](15, 2) NOT NULL,
		[WOG016]               [numeric](15, 2) NOT NULL,
		[WKG001]               [numeric](15, 2) NOT NULL,
		[WKG002]               [numeric](15, 2) NOT NULL,
		[WKG003]               [numeric](15, 2) NOT NULL,
		[WKG004]               [numeric](15, 2) NOT NULL,
		[WKG005]               [numeric](15, 2) NOT NULL,
		[WKG006]               [numeric](15, 2) NOT NULL,
		[WKG007]               [numeric](15, 2) NOT NULL,
		[WKG008]               [numeric](15, 2) NOT NULL,
		[WKG009]               [numeric](15, 2) NOT NULL,
		[WKG010]               [numeric](15, 2) NOT NULL,
		[WKG011]               [numeric](15, 2) NOT NULL,
		[WKG012]               [numeric](15, 2) NOT NULL,
		[WKG013]               [numeric](15, 2) NOT NULL,
		[WKG014]               [numeric](15, 2) NOT NULL,
		[WKG015]               [numeric](15, 2) NOT NULL,
		[WKG016]               [numeric](15, 2) NOT NULL,
		[WKF001]               [numeric](15, 2) NOT NULL,
		[WKF002]               [numeric](15, 2) NOT NULL,
		[WKF003]               [numeric](15, 2) NOT NULL,
		[WKF004]               [numeric](15, 2) NOT NULL,
		[WKF005]               [numeric](15, 2) NOT NULL,
		[WKF006]               [numeric](15, 2) NOT NULL,
		[WKF007]               [numeric](15, 2) NOT NULL,
		[WKF008]               [numeric](15, 2) NOT NULL,
		[WKF009]               [numeric](15, 2) NOT NULL,
		[WKF010]               [numeric](15, 2) NOT NULL,
		[WKF011]               [numeric](15, 2) NOT NULL,
		[WKF012]               [numeric](15, 2) NOT NULL,
		[WKF013]               [numeric](15, 2) NOT NULL,
		[WKF014]               [numeric](15, 2) NOT NULL,
		[WKF015]               [numeric](15, 2) NOT NULL,
		[WKF016]               [numeric](15, 2) NOT NULL,
		[PAG001]               [numeric](15, 2) NOT NULL,
		[PAG002]               [numeric](15, 2) NOT NULL,
		[PAG003]               [numeric](15, 2) NOT NULL,
		[PAG004]               [numeric](15, 2) NOT NULL,
		[PAG005]               [numeric](15, 2) NOT NULL,
		[PAG006]               [numeric](15, 2) NOT NULL,
		[PAG007]               [numeric](15, 2) NOT NULL,
		[PAG008]               [numeric](15, 2) NOT NULL,
		[PAG009]               [numeric](15, 2) NOT NULL,
		[PAG010]               [numeric](15, 2) NOT NULL,
		[PAG011]               [numeric](15, 2) NOT NULL,
		[PAG012]               [numeric](15, 2) NOT NULL,
		[PAG013]               [numeric](15, 2) NOT NULL,
		[PAG014]               [numeric](15, 2) NOT NULL,
		[PAG015]               [numeric](15, 2) NOT NULL,
		[PAG016]               [numeric](15, 2) NOT NULL,
		[MEG001]               [numeric](15, 3) NOT NULL,
		[MEG002]               [numeric](15, 3) NOT NULL,
		[MEG003]               [numeric](15, 3) NOT NULL,
		[MEG004]               [numeric](15, 3) NOT NULL,
		[MEG005]               [numeric](15, 3) NOT NULL,
		[MEG006]               [numeric](15, 3) NOT NULL,
		[MEG007]               [numeric](15, 3) NOT NULL,
		[MEG008]               [numeric](15, 3) NOT NULL,
		[MEG009]               [numeric](15, 3) NOT NULL,
		[MEG010]               [numeric](15, 3) NOT NULL,
		[MEG011]               [numeric](15, 3) NOT NULL,
		[MEG012]               [numeric](15, 3) NOT NULL,
		[MEG013]               [numeric](15, 3) NOT NULL,
		[MEG014]               [numeric](15, 3) NOT NULL,
		[MEG015]               [numeric](15, 3) NOT NULL,
		[MEG016]               [numeric](15, 3) NOT NULL,
		[MEF001]               [numeric](15, 3) NOT NULL,
		[MEF002]               [numeric](15, 3) NOT NULL,
		[MEF003]               [numeric](15, 3) NOT NULL,
		[MEF004]               [numeric](15, 3) NOT NULL,
		[MEF005]               [numeric](15, 3) NOT NULL,
		[MEF006]               [numeric](15, 3) NOT NULL,
		[MEF007]               [numeric](15, 3) NOT NULL,
		[MEF008]               [numeric](15, 3) NOT NULL,
		[MEF009]               [numeric](15, 3) NOT NULL,
		[MEF010]               [numeric](15, 3) NOT NULL,
		[MEF011]               [numeric](15, 3) NOT NULL,
		[MEF012]               [numeric](15, 3) NOT NULL,
		[MEF013]               [numeric](15, 3) NOT NULL,
		[MEF014]               [numeric](15, 3) NOT NULL,
		[MEF015]               [numeric](15, 3) NOT NULL,
		[MEF016]               [numeric](15, 3) NOT NULL,
		[MUV001]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV002]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV003]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV004]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV005]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV006]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV007]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV008]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV009]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV010]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV011]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV012]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV013]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV014]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV015]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MUV016]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BELTP]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TIMESTMP]             [numeric](16, 0) NOT NULL,
		[BUKRS]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FKBER]                [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SEGMENT]              [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GEBER]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GRANT_NBR]            [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUDGET_PD]            [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[create_timestamp]     [datetime] NULL,
		CONSTRAINT [PK_COSP]
		PRIMARY KEY
		CLUSTERED
		([MANDT], [LEDNR], [OBJNR], [GJAHR], [WRTTP], [VERSN], [KSTAR], [HRKFT], [VRGNG], [VBUND], [PARGB], [BEKNZ], [TWAER], [PERBL])
	ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_COSP_7_1111675008__K17]
	ON [dbo].[COSP] ([WTG001])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_COSP_7_1111675008__K4_K17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32]
	ON [dbo].[COSP] ([OBJNR], [WTG001])
	INCLUDE ([WTG002], [WTG003], [WTG004], [WTG005], [WTG006], [WTG007], [WTG008], [WTG009], [WTG010], [WTG011], [WTG012], [WTG013], [WTG014], [WTG015], [WTG016])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[COSP] SET (LOCK_ESCALATION = TABLE)
GO
