SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[stgF2Clientes1] (
		[CodEmpresa]                 [int] NOT NULL,
		[CodCliente]                 [int] NOT NULL,
		[CodOrgVentas]               [int] NULL,
		[OrgVentas]                  [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodCanal]                   [int] NOT NULL,
		[Canal]                      [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodSector]                  [int] NULL,
		[Sector]                     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodRespPago]                [int] NULL,
		[RazonSocial]                [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DNI_CIF]                    [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodVendedor]                [int] NULL,
		[Vendedor]                   [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodFondoComercio]           [int] NULL,
		[FondoComercio]              [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodRespAlta]                [int] NULL,
		[RespAlta]                   [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodRespAltaAd]              [int] NULL,
		[RespAltaAd]                 [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodRespCuenta]              [int] NULL,
		[RespCuenta]                 [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodCadena]                  [int] NULL,
		[Cadena]                     [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodComisionista]            [int] NULL,
		[Comisionista]               [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodComisionistaAd]          [int] NULL,
		[ComisionistaAd]             [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodDistribuidor]            [int] NULL,
		[Distribuidor]               [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodRepartidor]              [int] NOT NULL,
		[Repartidor]                 [varchar](11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CodTipoCliente]             [nvarchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TipoCliente]                [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodZonaVentas]              [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ZonaVentas]                 [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodTarifa]                  [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Tarifa]                     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodDelegacion]              [int] NULL,
		[CodCentroSuministro]        [int] NULL,
		[TipoFacturacion]            [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ConsumoAnualPrevisto]       [decimal](13, 3) NULL,
		[CodGamaConsumo]             [nvarchar](576) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PrecioGamaConsumo]          [decimal](15, 2) NULL,
		[FechaAltaComercial]         [int] NULL,
		[FechaBajaComercial]         [int] NULL,
		[NoControlDeuda]             [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ClienteEstacional]          [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CodFormaPago]               [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FormaPago]                  [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodProveedorActual]         [nvarchar](1600) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ProveedorActual]            [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ContratoVigente]            [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FechaFinContrato]           [nvarchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Maquina]                    [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CodModeloMaquina]           [nvarchar](1920) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ModeloMaquina]              [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodTipoContrato]            [nvarchar](1920) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[TipoContrato]               [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[OtroTipoInversion]          [nvarchar](1920) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[RitmoEntregaActual]         [nvarchar](1920) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[HorarioEntrega]             [nvarchar](1920) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FacturacionTotal]           [nvarchar](960) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[KgSemana]                   [nvarchar](960) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Precio]                     [nvarchar](960) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodGamaProductoActual]      [nvarchar](576) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[GamaProductoActual]         [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MarketingPLV]               [nvarchar](1920) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NumeroCliente]              [nvarchar](320) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[KGAño]                      [decimal](8, 2) NULL,
		[CodActividadPrincipal]      [nvarchar](1600) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ActividadPrincipal]         [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NumeroEstablecimientos]     [nvarchar](96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[MarcaPropia]                [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NombreMarcaPropia]          [nvarchar](480) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodPropiedadCliente]        [nvarchar](320) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[PropiedadCliente]           [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Personal]                   [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[create_timestamp]           [datetime] NOT NULL,
		CONSTRAINT [PK_stgF2Clientes1]
		PRIMARY KEY
		CLUSTERED
		([CodEmpresa], [CodCliente], [CodCanal])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[stgF2Clientes1] SET (LOCK_ESCALATION = TABLE)
GO
