SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[iReportesTriggerLog] (
		[CodEmpresa]               [int] NOT NULL,
		[nomIPad]                  [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[codReporte]               [int] NOT NULL,
		[fecReporte]               [datetime] NOT NULL,
		[codPlantillaReportes]     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CodCliente]               [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomCliente]               [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[datCalleDirCli]           [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[codPostalDirCli]          [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[datPoblacionDirCli]       [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[datProvinciaDirCli]       [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[datContactoDirCli]        [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[datTelefonoDirCli]        [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[datTelMovilDirCli]        [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[datEmailDirCli]           [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodAgente]                [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomAgente]                [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[CodArticulo]              [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Clave]                    [nvarchar](112) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FechaRegistro]            [datetime] NULL,
		[Procesado]                [bit] NULL,
		[FechaProceso]             [datetime] NULL,
		[001]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[002]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[003]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[004]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[005]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[006]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[007]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[008]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[009]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[010]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[011]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[012]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[013]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[014]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[015]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[016]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[017]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[018]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[019]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[020]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[021]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[022]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[023]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[024]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[025]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[026]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[027]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[028]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[029]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[030]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[031]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[032]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[033]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[034]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[035]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[036]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[037]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[038]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[039]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[040]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[041]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[042]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[043]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[044]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[045]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[046]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[047]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[048]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[049]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[050]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[051]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[052]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[053]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[054]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[055]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[056]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[057]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[058]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[059]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[060]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[061]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[062]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[063]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[064]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[065]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[066]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[067]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[068]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[069]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[070]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[071]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[072]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[073]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[074]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[075]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[076]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[077]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[078]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[079]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[080]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[081]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[082]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[083]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[084]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[085]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[086]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[087]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[088]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[089]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[090]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[091]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[092]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[093]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[094]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[095]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[096]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[097]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[098]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[099]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[100]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[101]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[102]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[103]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[104]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[105]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[106]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[107]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[108]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[109]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[110]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[111]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[112]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[113]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[114]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[115]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[116]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[117]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[118]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[119]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[120]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[121]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[122]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[123]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[124]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[125]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[126]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[127]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[128]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[129]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[130]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[131]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[132]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[133]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[134]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[135]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[136]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[137]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[138]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[139]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[140]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[141]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[142]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[143]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[144]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[145]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[146]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[147]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[148]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[149]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[150]                      [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK_iReportesTriggerLog]
		PRIMARY KEY
		CLUSTERED
		([CodEmpresa], [nomIPad], [codReporte])
	ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_iReportesTriggerLog_8_2096062553__K16_K5_K1_K6_2_3_4_7_17_82_90]
	ON [dbo].[iReportesTriggerLog] ([CodAgente], [codPlantillaReportes], [CodEmpresa], [CodCliente])
	INCLUDE ([nomIPad], [codReporte], [fecReporte], [nomCliente], [nomAgente], [060], [068])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[iReportesTriggerLog] SET (LOCK_ESCALATION = TABLE)
GO
