SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MARA] (
		[CodEmpresa]           [int] NOT NULL,
		[MANDT]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATNR]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERSDA]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERNAM]                [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LAEDA]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AENAM]                [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VPSTA]                [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PSTAT]                [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LVORM]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MTART]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MBRSH]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATKL]                [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BISMT]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MEINS]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BSTME]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZEINR]                [nvarchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZEIAR]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZEIVR]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZEIFO]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AESZN]                [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BLATT]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BLANZ]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FERTH]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FORMT]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GROES]                [nvarchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[WRKST]                [nvarchar](48) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NORMT]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LABOR]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EKWSL]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BRGEW]                [numeric](13, 3) NOT NULL,
		[NTGEW]                [numeric](13, 3) NOT NULL,
		[GEWEI]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VOLUM]                [numeric](13, 3) NOT NULL,
		[VOLEH]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BEHVO]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RAUBE]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TEMPB]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DISST]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TRAGR]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[STOFF]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SPART]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KUNNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EANNR]                [nvarchar](13) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[WESCH]                [numeric](13, 3) NOT NULL,
		[BWVOR]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BWSCL]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SAISO]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ETIAR]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ETIFO]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ENTAR]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EAN11]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NUMTP]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LAENG]                [numeric](13, 3) NOT NULL,
		[BREIT]                [numeric](13, 3) NOT NULL,
		[HOEHE]                [numeric](13, 3) NOT NULL,
		[MEABM]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRDHA]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AEKLK]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CADKZ]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[QMPUR]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERGEW]                [numeric](13, 3) NOT NULL,
		[ERGEI]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERVOL]                [numeric](13, 3) NOT NULL,
		[ERVOE]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GEWTO]                [numeric](3, 1) NOT NULL,
		[VOLTO]                [numeric](3, 1) NOT NULL,
		[VABME]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KZREV]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KZKFG]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[XCHPF]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VHART]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FUELG]                [numeric](3, 0) NOT NULL,
		[STFAK]                [smallint] NOT NULL,
		[MAGRV]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BEGRU]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DATAB]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LIQDT]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SAISJ]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PLGTP]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MLGUT]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EXTWG]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SATNR]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ATTYP]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KZKUP]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KZNFM]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PMATA]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MSTAE]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MSTAV]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MSTDE]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MSTDV]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TAKLV]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RBNRM]                [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MHDRZ]                [numeric](4, 0) NOT NULL,
		[MHDHB]                [numeric](4, 0) NOT NULL,
		[MHDLP]                [numeric](3, 0) NOT NULL,
		[INHME]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[INHAL]                [numeric](13, 3) NOT NULL,
		[VPREH]                [numeric](5, 0) NOT NULL,
		[ETIAG]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[INHBR]                [numeric](13, 3) NOT NULL,
		[CMETH]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CUOBF]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KZUMW]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KOSCH]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SPROF]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NRFHG]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MFRPN]                [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MFRNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BMATN]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MPROF]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KZWSM]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SAITY]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PROFL]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IHIVI]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ILOOS]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SERLV]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KZGVH]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[XGCHP]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KZEFF]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[COMPL]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IPRKZ]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RDMHD]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRZUS]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MTPOS_MARA]           [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BFLME]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATFI]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CMREL]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BBTYP]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SLED_BBD]             [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GTIN_VARIANT]         [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GENNR]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RMATP]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GDS_RELEVANT]         [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[WEORA]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[HUTYP_DFLT]           [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PILFERABLE]           [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[WHSTC]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[WHMATGR]              [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[HNDLCODE]             [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[HAZMAT]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[HUTYP]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TARE_VAR]             [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAXC]                 [numeric](15, 3) NOT NULL,
		[MAXC_TOL]             [numeric](3, 1) NOT NULL,
		[MAXL]                 [numeric](15, 3) NOT NULL,
		[MAXB]                 [numeric](15, 3) NOT NULL,
		[MAXH]                 [numeric](15, 3) NOT NULL,
		[MAXDIM_UOM]           [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[HERKL]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MFRGR]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[QQTIME]               [numeric](3, 0) NOT NULL,
		[QQTIMEUOM]            [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[QGRP]                 [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SERIAL]               [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PS_SMARTFORM]         [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LOGUNIT]              [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CWQREL]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CWQPROC]              [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CWQTOLGR]             [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ADPROF]               [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ANIMAL_ORIGIN]        [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TEXTILE_COMP_IND]     [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/BEV1/LULEINH]        [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/BEV1/LULDEGRP]       [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/BEV1/NESTRUCCAT]     [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/DSD/SL_TOLTYP]       [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/DSD/SV_CNT_GRP]      [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/DSD/VC_GROUP]        [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_TILT_IND]      [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_STACK_IND]     [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_BOT_IND]       [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_TOP_IND]       [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_STACK_NO]      [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_PAL_IND]       [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_PAL_OVR_D]     [numeric](13, 3) NOT NULL,
		[/VSO/R_PAL_OVR_W]     [numeric](13, 3) NOT NULL,
		[/VSO/R_PAL_B_HT]      [numeric](13, 3) NOT NULL,
		[/VSO/R_PAL_MIN_H]     [numeric](13, 3) NOT NULL,
		[/VSO/R_TOL_B_HT]      [numeric](13, 3) NOT NULL,
		[/VSO/R_NO_P_GVH]      [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_QUAN_UNIT]     [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[/VSO/R_KZGVH_IND]     [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PACKCODE]             [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DG_PACK_STATUS]       [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MCOND]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RETDELC]              [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LOGLEV_RETO]          [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NSNID]                [nvarchar](9) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ADSPC_SPC]            [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMATN]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PICNUM]               [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BSTAT]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[COLOR_ATINN]          [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SIZE1_ATINN]          [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SIZE2_ATINN]          [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[COLOR]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SIZE1]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SIZE2]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FREE_CHAR]            [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CARE_CODE]            [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BRAND_ID]             [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_CODE1]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_PART1]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_CODE2]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_PART2]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_CODE3]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_PART3]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_CODE4]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_PART4]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_CODE5]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FIBER_PART5]          [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FASHGRD]              [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZMOD]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZGRTALL]             [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZTALL]               [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZCLASIF]             [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZTS]                 [numeric](15, 3) NOT NULL,
		[ZZFABRICANT]          [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZORIGEN1]            [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZORIGEN1_TX]         [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZORIGEN2]            [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZORIGEN2_TX]         [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZOPORCENTAJE1]       [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZOPORCENTAJE2]       [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZREF_FABRIC]         [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZFAB_TX]             [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZGAS]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZLUZ]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZAGUA]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZMONO]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZTRIFA]              [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZTELEFONO]           [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZDESAGUE]            [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[create_timestamp]     [datetime] NOT NULL,
		CONSTRAINT [PK_MARA]
		PRIMARY KEY
		CLUSTERED
		([MANDT], [MATNR])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MARA] SET (LOCK_ESCALATION = TABLE)
GO
