SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ZCABVIS_XONESAP_STG] (
		[CodEmpresa]           [int] NULL,
		[MANDT]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PERNR]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TIPVI]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VISIT]                [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FACTC]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TICKE]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NUMDO]                [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TIPDO]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KUNNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECVI]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[HORVI]                [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VKBUR]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LGORT]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[WAERS]                [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BIV01]                [numeric](13, 2) NOT NULL,
		[BIV02]                [numeric](13, 2) NOT NULL,
		[BIV03]                [numeric](13, 2) NOT NULL,
		[BIV05]                [numeric](13, 2) NOT NULL,
		[IVA01]                [numeric](13, 2) NOT NULL,
		[IVA02]                [numeric](13, 2) NOT NULL,
		[IVA03]                [numeric](13, 2) NOT NULL,
		[IVA05]                [numeric](13, 2) NOT NULL,
		[REQ01]                [numeric](13, 2) NOT NULL,
		[REQ02]                [numeric](13, 2) NOT NULL,
		[REQ03]                [numeric](13, 2) NOT NULL,
		[REQ05]                [numeric](13, 2) NOT NULL,
		[BASEI]                [numeric](13, 2) NOT NULL,
		[TOTAL]                [numeric](13, 2) NOT NULL,
		[TOCOB]                [numeric](13, 2) NOT NULL,
		[TICOB]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NUMIM]                [int] NOT NULL,
		[OBSER]                [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NUMLI]                [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TALON]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANCO]                [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PERCL]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAQRE]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EQUNR]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRTEC]                [int] NOT NULL,
		[CAMBI]                [numeric](13, 2) NOT NULL,
		[CONTA]                [int] NOT NULL,
		[LIMEX]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LIMIN]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LOTEX]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ACCION]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERNAM]                [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERSDA]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERZET]                [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MANUA]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN_P]              [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN_E]              [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MBLNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MJAHR]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN_F]              [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BUKRS]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BELNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GJAHR]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN_REC]            [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN_FREC]           [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN_CAM]            [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN_FCAM]           [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NUMVISAUX]            [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NUMVM]                [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[create_timestamp]     [datetime] NULL,
		[update_timestamp]     [datetime] NULL,
		[audit_key]            [int] NULL,
		CONSTRAINT [PK_ZCABVIS_XONESAP_STG]
		PRIMARY KEY
		CLUSTERED
		([MANDT], [PERNR], [TIPVI], [VISIT])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ZCABVIS_XONESAP_STG] SET (LOCK_ESCALATION = TABLE)
GO
