SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ZCAH001] (
		[CodEmpresa]           [int] NOT NULL,
		[MANDT]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CLASE]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[STATUS]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PDTE_CONF_MODIF]      [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[STATUS_MODIF]         [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERDAT]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERZET]                [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERNAM]                [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VKORG]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VTWEG]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SPART]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VKBUR]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LUGAR]                [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PERNR]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VORNA]                [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NACHN]                [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NACH2]                [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[STCDP]                [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ORT01]                [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KUNNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[STCD1]                [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NAME1]                [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NAME2]                [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ADMIN]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AD_VORNA]             [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AD_NACHN]             [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AD_NACH2]             [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AD_STRAS]             [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AD_ORT01]             [nvarchar](35) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AD_LAND1]             [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[STCDA]                [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AEDAT]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AEZET]                [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AENAM]                [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FAPROB]               [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MESES]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KILOS]                [numeric](13, 3) NOT NULL,
		[UM]                   [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMPORTE]              [numeric](13, 2) NOT NULL,
		[MONEDA]               [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_INI]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_FIN]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LOEKZ]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MOTIVO]               [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANKL]                [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANKN]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BKONT]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VALOR_COMPRA]         [numeric](13, 2) NOT NULL,
		[IMPORTE_RAPPEL_A]     [numeric](13, 2) NOT NULL,
		[AVAL_RAPPEL]          [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_RAPPEL]         [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANKL_RAPPEL]         [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANCO_RAPPEL]         [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMPORTE_RAPPEL]       [numeric](13, 2) NOT NULL,
		[DUR_AVAL_RAPPEL]      [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GAST_AVAL_RAPPEL]     [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRORROG_AVAL]         [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRODH]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRECIO_KILO]          [numeric](13, 2) NOT NULL,
		[LIBERADO]             [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[COMPENSACION]         [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CARGA]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_ANU]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AVAL_LETRA]           [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PROMO_PRESU]          [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CASUALBEER]           [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATNR_NORM]           [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRECIO_NORM]          [numeric](13, 2) NOT NULL,
		[PRECIO_NORM_PROP]     [numeric](13, 2) NOT NULL,
		[PORC_NORM]            [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATNR_DESC]           [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRECIO_DESC]          [numeric](13, 2) NOT NULL,
		[PRECIO_DESC_PROP]     [numeric](13, 2) NOT NULL,
		[PORC_DESC]            [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RESP_ALTA]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RESP_ALTA_AD]         [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMPORTE_PREST]        [numeric](13, 2) NOT NULL,
		[IMPMENS_PREST]        [numeric](13, 2) NOT NULL,
		[MENSUALIDADES]        [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANKL_P]              [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANKN_P]              [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BKONT_P]              [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANKL_P2]             [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANKN_P2]             [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BKONT_P2]             [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BANKA_P]              [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZTERM]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZLSCH]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[INDEMNIZ1]            [numeric](13, 2) NOT NULL,
		[INDEMNIZ2]            [numeric](13, 2) NOT NULL,
		[RAPPEL_SIN_AVAL]      [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PDTE_AMORTIZAR]       [numeric](13, 2) NOT NULL,
		[CONTRATO_CARGA]       [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NUM_SI_CARGA]         [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[GAMA_CAFE]            [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KNUMA]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ANLN1]                [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ANLN2]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FRENT]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FDEPO]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PMR]                  [numeric](13, 2) NOT NULL,
		[PMRM]                 [numeric](13, 2) NOT NULL,
		[FPMR]                 [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PMRMOD]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PMR1]                 [numeric](13, 2) NOT NULL,
		[PMRM1]                [numeric](13, 2) NOT NULL,
		[TIPO]                 [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[JURID]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KGPROMO]              [numeric](13, 3) NOT NULL,
		[ENE]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FEB]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAR]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ABR]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAY]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[JUN]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[JUL]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AGO]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SEP]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[OCT]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NOV]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DIC]                  [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NOCAPEX]              [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[IMPORTE_APORT_P]      [numeric](13, 2) NULL,
		[APORT_SIN_AVAL]       [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[AVAL_APORTACION]      [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FECHA_APORTACION]     [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[DUR_AVAL_APORT]       [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[GAST_AVAL_APORT]      [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BANKL_APORTACION]     [nvarchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BANCO_APORTACION]     [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[IMPORTE_APORT]        [numeric](13, 2) NULL,
		[TIR]                  [numeric](16, 10) NULL,
		[Starting]             [datetime2](7) NOT NULL,
		[Ending]               [datetime2](7) NOT NULL,
		[REVIS]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FREVI]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ACCION_CORRECT]       [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ACT_C_ANT]            [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FLEAS]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ZMOTIVOM]             [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ZMOTMOV]              [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[create_timestamp]     [datetime] NOT NULL,
		CONSTRAINT [PK_ZCAH001]
		PRIMARY KEY
		CLUSTERED
		([MANDT], [VBELN])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ZCAH001] SET (LOCK_ESCALATION = TABLE)
GO
