SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[stgF2CumpInversiones] (
		[FechaProceso_key]     [int] NOT NULL,
		[CodEmpresa]           [int] NOT NULL,
		[MANDT]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VBELN]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_INI]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VKBUR]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[BEZEI]                [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TIPO]                 [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[JURID]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[JURID_TXT]            [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_INI_OR]         [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_APROB]          [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[F_APROB30]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_FIN]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MESES]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MESES_D]              [numeric](6, 2) NOT NULL,
		[MESESP]               [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CLASE]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CLASE_TXT]            [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[STATUS]               [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ATC]                  [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VORNA_ATC]            [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NACHN_ATC]            [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AUTOV]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VORNA_ZV]             [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NACHN_ZV]             [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RESP_ALTA]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VORNA_RA]             [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NACHN_RA]             [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RESPC]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VORNA_RC]             [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NACHN_RC]             [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KUNNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NAME1]                [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ESTABL]               [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NAME1_EST]            [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZZCLIESTAC]           [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZJ]                   [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[NAME_ZJ]              [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATNR]                [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAKTX]                [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KILOS]                [numeric](13, 3) NOT NULL,
		[UM]                   [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRECIO]               [numeric](13, 2) NOT NULL,
		[MONEDA]               [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KILOSM]               [numeric](13, 3) NOT NULL,
		[PRECIOM]              [numeric](13, 2) NOT NULL,
		[PROMO]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TIPO_PROMO]           [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KNRNM]                [numeric](13, 3) NOT NULL,
		[KNRZM]                [numeric](13, 3) NOT NULL,
		[KNREZ]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KNRMAT]               [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATKX2]               [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PRIM_VENTA]           [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ULT_VENTA]            [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DESV_KG]              [numeric](8, 2) NOT NULL,
		[DESV_PREC]            [numeric](8, 2) NOT NULL,
		[PRVENTA]              [numeric](13, 2) NOT NULL,
		[MAQ1]                 [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAQ1TX]               [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAQ2]                 [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAQ2TX]               [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAQ3]                 [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAQ3TX]               [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAQ4]                 [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAQ4TX]               [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FACT_EST]             [numeric](13, 2) NOT NULL,
		[FACT_REAL]            [numeric](13, 2) NOT NULL,
		[INVERSION]            [numeric](13, 2) NOT NULL,
		[RATIO_I]              [numeric](13, 2) NOT NULL,
		[RATIO_R]              [numeric](13, 2) NOT NULL,
		[PMR]                  [numeric](13, 2) NOT NULL,
		[ZBAJA]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AMORTIZACION]         [numeric](13, 2) NOT NULL,
		[CADUCADO]             [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATNR_NORM]           [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAKTX_NORM]           [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MATNR_DESC]           [nvarchar](18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MAKTX_DESC]           [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KGTOT]                [numeric](13, 3) NOT NULL,
		[KGPEND]               [numeric](13, 3) NOT NULL,
		[PORC_CUMP]            [numeric](13, 2) NOT NULL,
		[KNUMA]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[MESES_SAVE]           [numeric](6, 2) NOT NULL,
		[XKBETR]               [numeric](11, 2) NOT NULL,
		[XKONWA]               [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CONT]                 [tinyint] NOT NULL,
		[YALTA]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERNAM]                [nvarchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERDAT]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ERZET]                [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[COMISIONISTA]         [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[INVERS_C]             [numeric](13, 2) NOT NULL,
		[PMR1]                 [numeric](13, 2) NOT NULL,
		[DATUM1]               [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[TIR]                  [numeric](16, 10) NOT NULL,
		[IMPSOC]               [numeric](13, 2) NOT NULL,
		[INVINI]               [numeric](13, 2) NOT NULL,
		[PRMED]                [numeric](13, 2) NOT NULL,
		[ZZFREACT]             [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FECHA_JURID]          [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PROSPECTOR]           [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[VORNA_ZT]             [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NACHN_ZT]             [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[KDGRP]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FACT_EST_C]           [numeric](13, 2) NULL,
		[FACT_REAL_C]          [numeric](13, 2) NULL,
		[ZMOTIVOM]             [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ZMOTMOD]              [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FREVI]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ACCION_CORRECT]       [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[create_timestamp]     [datetime] NOT NULL,
		CONSTRAINT [PK_stgF2CumpInversiones]
		PRIMARY KEY
		CLUSTERED
		([FechaProceso_key], [CodEmpresa], [MANDT], [VBELN])
	ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_stgF2CumpInversiones_7_1403868068__K2_K8_K18_4_6_19_75_77]
	ON [dbo].[stgF2CumpInversiones] ([CodEmpresa], [TIPO], [CLASE])
	INCLUDE ([VBELN], [VKBUR], [CLASE_TXT], [MATNR_NORM], [MATNR_DESC])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[stgF2CumpInversiones] SET (LOCK_ESCALATION = TABLE)
GO
