SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[KNVP] (
		[CodEmpresa]           [int] NOT NULL,
		[MANDT]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KUNNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VKORG]                [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[VTWEG]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[SPART]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PARVW]                [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PARZA]                [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KUNN2]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LIFNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PERNR]                [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[PARNR]                [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[KNREF]                [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DEFPA]                [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[create_timestamp]     [datetime] NULL,
		CONSTRAINT [PK_KNVP]
		PRIMARY KEY
		CLUSTERED
		([MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [PARVW], [PARZA])
	ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K2_K11_K3_K4_K5_K6_K8_K9_K10]
	ON [dbo].[KNVP] ([PARVW], [MANDT], [PERNR], [KUNNR], [VKORG], [VTWEG], [SPART], [PARZA], [KUNN2], [LIFNR])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K2_K3_K4_K5_K6_K8_9_11]
	ON [dbo].[KNVP] ([PARVW], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [PARZA])
	INCLUDE ([KUNN2], [PERNR])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K3_11]
	ON [dbo].[KNVP] ([PARVW], [KUNNR])
	INCLUDE ([PERNR])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K3_9]
	ON [dbo].[KNVP] ([PARVW], [KUNNR])
	INCLUDE ([KUNN2])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K11_K2_K3_K4_K5_K6]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [PERNR], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K11_K2_K3_K4_K5_K6_K9_K10]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [PERNR], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [KUNN2], [LIFNR])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K2_K11_K3_K4_K5_K6]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [MANDT], [PERNR], [KUNNR], [VKORG], [VTWEG], [SPART])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K2_K3_K4_K5_K6_11]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART])
	INCLUDE ([PERNR])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K2_K3_K4_K5_K6_K10]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [LIFNR])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K2_K3_K4_K5_K6_K10_K9]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [LIFNR], [KUNN2])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K2_K3_K4_K5_K6_K10_K9_K11]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [LIFNR], [KUNN2], [PERNR])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K2_K3_K4_K5_K6_K9]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [KUNN2])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_7_1013578649__K7_K8_K2_K3_K4_K5_K6_K9_K10]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [KUNN2], [LIFNR])
	ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [_dta_index_KNVP_8_1013578649__K7_K8_K2_K3_K4_K5_K6_K10_K9_K11_1_12_13_14_15]
	ON [dbo].[KNVP] ([PARVW], [PARZA], [MANDT], [KUNNR], [VKORG], [VTWEG], [SPART], [LIFNR], [KUNN2], [PERNR])
	INCLUDE ([CodEmpresa], [PARNR], [KNREF], [DEFPA], [create_timestamp])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[KNVP] SET (LOCK_ESCALATION = TABLE)
GO
