SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [rpt].[AgendaCoffeeTester] (
		[CodDelegacion]                             [int] NOT NULL,
		[Delegacion]                                [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CodZonaVentas]                             [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ZonaVentas]                                [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[ClasifABC]                                 [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[codTipoCliente]                            [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[desTipoCliente]                            [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[codCliente]                                [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[nomCliente]                                [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[codAgente]                                 [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[nomAgente]                                 [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[datCalleDirCli]                            [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[codPostalDirCli]                           [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[datPoblacionDirCli]                        [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[datProvinciaDirCli]                        [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[datContactoDirCli]                         [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Telefono]                                  [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[fecAltaCliente]                            [datetime] NOT NULL,
		[Custom1]                                   [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[Custom2]                                   [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[Custom3]                                   [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[Custom4]                                   [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[Custom5]                                   [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FechaProspeccion]                          [datetime] NULL,
		[codAgenteProspeccion]                      [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomAgenteProspeccion]                      [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FechaPrimeraVisita]                        [datetime] NULL,
		[codAgentePrimeraVisita]                    [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomAgentePrimeraVisita]                    [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FechaUltimaVisita]                         [datetime] NULL,
		[codAgenteUltimaVisita]                     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomAgenteUltimaVisita]                     [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FechaPrimerCoffeeTester]                   [datetime] NULL,
		[FechaUltimoCoffeeTester]                   [datetime] NULL,
		[CoffeeTesterRealizados]                    [int] NULL,
		[codAgenteUltimoCoffeeTester]               [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomAgenteUltimoCoffeeTester]               [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[RealizadoCoffeTester]                      [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DiasDesdeCoffeTester]                      [int] NULL,
		[Observaciones]                             [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FechaPlanifSigCT]                          [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[FechaUltimoCambioFiltro]                   [datetime] NULL,
		[codAgenteCambioFiltros]                    [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomAgenteCambioFiltros]                    [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[RealizadoCambioFiltro]                     [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DiasDesdeCambioFiltro]                     [int] NULL,
		[FechaUltimoCambioMuelasCafe]               [datetime] NULL,
		[codAgenteCambioMuelasCafe]                 [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomCambioMuelasCafe]                       [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[RealizadoCambioMuelasCafe]                 [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DiasDesdeCambioMuelasCafe]                 [int] NULL,
		[FechaUltimoCambioMuelasDecaf]              [datetime] NULL,
		[codAgenteCambioMuelasDecaf]                [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[nomAgenteCambioMuelasDecaf]                [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[RealizadoCambioMuelasDecaf]                [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DiasDesdeCambioMuelasDecaf]                [int] NULL,
		[FechaUltCompraCafe]                        [datetime] NULL,
		[KilosCafeEntregadosT]                      [numeric](38, 9) NULL,
		[KilosCafeEntregados]                       [numeric](38, 9) NULL,
		[KilosCafeDecafEntregados]                  [numeric](38, 9) NULL,
		[KilosCafeDesdeCambioMuelas]                [numeric](38, 9) NULL,
		[KilosCafeDecafDesdeCambioMuelas]           [numeric](38, 9) NULL,
		[KilosCafeDesdeCambioFiltro]                [numeric](38, 9) NULL,
		[KilosCafeDesdePrimerCoffeeTester]          [numeric](38, 9) NULL,
		[KilosCafeDecafDesdePrimerCoffeeTester]     [numeric](38, 9) NULL,
		[CambiarMuelasCafe]                         [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CambiarMuelasCafeDecaf]                    [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CambiarFiltro]                             [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AltaNueva]                                 [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[EnRangoDias]                               [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[RangoDias]                                 [int] NULL,
		[FechaSiguienteCoffeTester]                 [datetime] NULL,
		[CafeDesde2M]                               [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FotoUsuario]                               [varchar](29) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[FechaRegistro]                             [datetime] NULL,
		CONSTRAINT [PK_AgendaCoffeeTester]
		PRIMARY KEY
		CLUSTERED
		([CodDelegacion], [codCliente])
	ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [rpt].[AgendaCoffeeTester] SET (LOCK_ESCALATION = TABLE)
GO
