SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[UserState] (
		[US_Code]       [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[UST_State]     [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK__UserStat__606A0960002AF460]
		PRIMARY KEY
		CLUSTERED
		([US_Code])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[UserState]
	WITH CHECK
	ADD CONSTRAINT [FK__UserState__US_Co__1DDB52D8]
	FOREIGN KEY ([US_Code]) REFERENCES [dbo].[Users] ([US_Code])
ALTER TABLE [dbo].[UserState]
	CHECK CONSTRAINT [FK__UserState__US_Co__1DDB52D8]

GO
ALTER TABLE [dbo].[UserState] SET (LOCK_ESCALATION = TABLE)
GO
