SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[ABSDates] (
		[AD_Date]     [int] NOT NULL,
		CONSTRAINT [PK__ABSDates__164897CB0425A276]
		PRIMARY KEY
		CLUSTERED
		([AD_Date])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[ABSDates] SET (LOCK_ESCALATION = TABLE)
GO
