SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ActionProcessSupportIDS] (
		[APS_ID]          [int] IDENTITY(1, 1) NOT NULL,
		[APS_Created]     [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK__ActionPr__E3DC59612B3F6F97]
		PRIMARY KEY
		CLUSTERED
		([APS_ID])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[ActionProcessSupportIDS] SET (LOCK_ESCALATION = TABLE)
GO
