SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CultureCodes] (
		[CLC_Code]     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [PK__CultureC__B663D1A374444068]
		PRIMARY KEY
		CLUSTERED
		([CLC_Code])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[CultureCodes] SET (LOCK_ESCALATION = TABLE)
GO
