SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[APEXSQL_LOG_OPERATION_DETAIL] (
		[LSN]             [char](22) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[LINE_NO]         [int] NOT NULL,
		[COLUMN_NAME]     [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[COLUMN_TYPE]     [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[OLD_VALUE]       [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[NEW_VALUE]       [ntext] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK_APEXSQL_LOG_OPERATION_DETAIL]
		PRIMARY KEY
		CLUSTERED
		([LSN], [LINE_NO])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[APEXSQL_LOG_OPERATION_DETAIL] SET (LOCK_ESCALATION = TABLE)
GO
