SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ResCst] (
		[RE_Code]     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CO_Code]     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [PK__ResCst__2675A2553631FF56]
		PRIMARY KEY
		CLUSTERED
		([RE_Code], [CO_Code])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[ResCst]
	WITH CHECK
	ADD CONSTRAINT [FK__ResCst__CO_Code__17635F73]
	FOREIGN KEY ([CO_Code]) REFERENCES [dbo].[Cost] ([CO_Code])
ALTER TABLE [dbo].[ResCst]
	CHECK CONSTRAINT [FK__ResCst__CO_Code__17635F73]

GO
ALTER TABLE [dbo].[ResCst]
	WITH CHECK
	ADD CONSTRAINT [FK__ResCst__RE_Code__185783AC]
	FOREIGN KEY ([RE_Code]) REFERENCES [dbo].[Res] ([RE_Code])
ALTER TABLE [dbo].[ResCst]
	CHECK CONSTRAINT [FK__ResCst__RE_Code__185783AC]

GO
CREATE NONCLUSTERED INDEX [RC_CostResIndex]
	ON [dbo].[ResCst] ([CO_Code], [RE_Code])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[ResCst] SET (LOCK_ESCALATION = TABLE)
GO
