SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PrjAct] (
		[PR_Code]     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[AC_Code]     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		CONSTRAINT [PK__PrjAct__A894635639788055]
		PRIMARY KEY
		CLUSTERED
		([PR_Code], [AC_Code])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[PrjAct]
	WITH CHECK
	ADD CONSTRAINT [FK__PrjAct__AC_Code__14BBFCF2]
	FOREIGN KEY ([AC_Code]) REFERENCES [dbo].[Activity] ([AC_Code])
ALTER TABLE [dbo].[PrjAct]
	CHECK CONSTRAINT [FK__PrjAct__AC_Code__14BBFCF2]

GO
ALTER TABLE [dbo].[PrjAct]
	WITH CHECK
	ADD CONSTRAINT [FK__PrjAct__PR_Code__15B0212B]
	FOREIGN KEY ([PR_Code]) REFERENCES [dbo].[Projects] ([PR_Code])
ALTER TABLE [dbo].[PrjAct]
	CHECK CONSTRAINT [FK__PrjAct__PR_Code__15B0212B]

GO
CREATE NONCLUSTERED INDEX [PA_ActPrjIndex]
	ON [dbo].[PrjAct] ([AC_Code], [PR_Code])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[PrjAct] SET (LOCK_ESCALATION = TABLE)
GO
