SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[BillingInvoiceLine] (
		[BIL_Key]                     [int] IDENTITY(1, 1) NOT NULL,
		[BIL_Desc]                    [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BI_Key]                      [int] NOT NULL,
		[BCL_Key]                     [int] NOT NULL,
		[BCD_Key]                     [int] NOT NULL,
		[BIL_Type]                    [int] NOT NULL,
		[NC_Code]                     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BIL_NetCharge]               [float] NOT NULL,
		[BIL_AdjustedCharge]          [float] NULL,
		[BIL_VAT]                     [float] NULL,
		[BIL_GrossCharge]             [float] NOT NULL,
		[BIL_AutoGenerated]           [int] NULL,
		[BIL_LastEditDate]            [float] NULL,
		[US_Code]                     [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[BIL_Units]                   [float] NULL,
		[BIL_SystemNetCharge]         [float] NULL,
		[BIL_SystemGrossCharge]       [float] NULL,
		[BIL_Summary]                 [int] NULL,
		[BIL_IncludesMultipleVAT]     [smallint] NULL,
		CONSTRAINT [PK__BillingI__02FF575251300E55]
		PRIMARY KEY
		CLUSTERED
		([BIL_Key])
	ON [PRIMARY]
)
GO
ALTER TABLE [dbo].[BillingInvoiceLine]
	WITH CHECK
	ADD CONSTRAINT [FK__BillingIn__BCD_K__5E94F66B]
	FOREIGN KEY ([BCD_Key]) REFERENCES [dbo].[BillingContractLineDetails] ([BCD_Key])
ALTER TABLE [dbo].[BillingInvoiceLine]
	CHECK CONSTRAINT [FK__BillingIn__BCD_K__5E94F66B]

GO
ALTER TABLE [dbo].[BillingInvoiceLine]
	WITH CHECK
	ADD CONSTRAINT [FK__BillingIn__BCL_K__5F891AA4]
	FOREIGN KEY ([BCL_Key]) REFERENCES [dbo].[BillingContractLine] ([BCL_Key])
ALTER TABLE [dbo].[BillingInvoiceLine]
	CHECK CONSTRAINT [FK__BillingIn__BCL_K__5F891AA4]

GO
ALTER TABLE [dbo].[BillingInvoiceLine]
	WITH CHECK
	ADD CONSTRAINT [FK__BillingIn__BI_Ke__607D3EDD]
	FOREIGN KEY ([BI_Key]) REFERENCES [dbo].[BillingInvoice] ([BI_Key])
ALTER TABLE [dbo].[BillingInvoiceLine]
	CHECK CONSTRAINT [FK__BillingIn__BI_Ke__607D3EDD]

GO
ALTER TABLE [dbo].[BillingInvoiceLine]
	WITH CHECK
	ADD CONSTRAINT [FK__BillingIn__NC_Co__61716316]
	FOREIGN KEY ([NC_Code]) REFERENCES [dbo].[Nominal] ([NC_Code])
ALTER TABLE [dbo].[BillingInvoiceLine]
	CHECK CONSTRAINT [FK__BillingIn__NC_Co__61716316]

GO
ALTER TABLE [dbo].[BillingInvoiceLine] SET (LOCK_ESCALATION = TABLE)
GO
