SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[vPaises] AS
SELECT [LAND1] COLLATE DATABASE_DEFAULT CodPais
      ,[LANDX] COLLATE DATABASE_DEFAULT Pais
  FROM [SAP_STG].[dbo].[T005T]
GO
